import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { basename, extname, join, relative } from 'node:path';
import type { HostInfo, InstanceRecord } from '../types.js';
import { StorybrokrError } from './errors.js';

export const SIDECAR = 'storybrokr.json';

export function instanceId(hostRoot: string, component: string): string {
  return createHash('sha256').update(`${hostRoot}\n${component}`).digest('hex').slice(0, 12);
}

export function configDirFor(hostRoot: string, id: string): string {
  return join(hostRoot, 'node_modules', '.cache', 'storybrokr', id);
}

/** The generated main.ts: host main spread with stories/staticDirs/nextConfigPath rewritten. */
function renderMain(host: HostInfo, configDir: string, storyFiles: string[]): string {
  const rel = storyFiles.map((f) => {
    const r = relative(configDir, join(host.hostRoot, f)).split('\\').join('/');
    return r.startsWith('.') ? r : `./${r}`;
  });
  return `// Generated by storybrokr — an ephemeral single-component Storybook config.
// Inherits the host's .storybook/main and overrides only what must change.
// Uses node:path (not require): Storybook loads this file as ESM.
import { resolve as pathResolve } from 'node:path';
import host from ${JSON.stringify(host.mainFile)};

const HOST_SB = ${JSON.stringify(host.storybookDir)};
const abs = (p: string): string => (p.startsWith('/') ? p : pathResolve(HOST_SB, p));
const hostFramework =
  typeof host.framework === 'string' ? { name: host.framework, options: {} } : host.framework;
const options = (hostFramework as { options?: Record<string, unknown> }).options ?? {};
const nextConfigPath = options.nextConfigPath;

const config = {
  ...host,
  stories: ${JSON.stringify(rel, null, 2)},
  staticDirs: (host.staticDirs ?? []).map((d: unknown) =>
    typeof d === 'string' ? abs(d) : { ...(d as { from: string; to: string }), from: abs((d as { from: string }).from) },
  ),
  framework: {
    ...hostFramework,
    options: {
      ...options,
      ...(typeof nextConfigPath === 'string' ? { nextConfigPath: abs(nextConfigPath) } : {}),
    },
  },
};

export default config;
`;
}

function renderReexport(target: string): string {
  return `// Generated by storybrokr — re-exports the host file unchanged.
export * from ${JSON.stringify(target)};
export { default } from ${JSON.stringify(target)};
`;
}

export function generateConfigDir(host: HostInfo, id: string, storyFiles: string[]): string {
  const dir = configDirFor(host.hostRoot, id);
  rmSync(dir, { recursive: true, force: true });
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, 'main.ts'), renderMain(host, dir, storyFiles));
  if (host.previewFile) {
    writeFileSync(
      join(dir, `preview${extname(host.previewFile)}`),
      renderReexport(host.previewFile),
    );
  }
  if (host.managerFile) {
    writeFileSync(
      join(dir, `manager${extname(host.managerFile)}`),
      renderReexport(host.managerFile),
    );
  }
  return dir;
}

export function writeSidecar(configDir: string, record: InstanceRecord): void {
  writeFileSync(join(configDir, SIDECAR), `${JSON.stringify(record, null, 2)}\n`);
}

/** Every sidecar under <hostRoot>/node_modules/.cache/storybrokr — the durable inventory. */
export function readSidecars(hostRoot: string): InstanceRecord[] {
  const base = join(hostRoot, 'node_modules', '.cache', 'storybrokr');
  if (!existsSync(base)) return [];
  const out: InstanceRecord[] = [];
  for (const entry of readdirSync(base)) {
    const file = join(base, entry, SIDECAR);
    if (!existsSync(file)) continue;
    try {
      out.push(JSON.parse(readFileSync(file, 'utf8')) as InstanceRecord);
    } catch {
      // A half-written sidecar is not an instance; skip it.
    }
  }
  return out.sort((a, b) => a.id.localeCompare(b.id));
}

export function removeConfigDir(configDir: string): void {
  if (basename(join(configDir, '..')) !== 'storybrokr') {
    throw new StorybrokrError(
      'INTERNAL',
      `refusing to remove ${configDir}: not under a storybrokr cache dir`,
    );
  }
  rmSync(configDir, { recursive: true, force: true });
}
